title: RockSolar.com
baseurl: /
  
# Social Media
google_analytics_tracking_id:

markdown: kramdown

highlighter: rouge
  
# For Jekyll Plugins, per http://jekyllrb.com/docs/plugins/
# gems: [ image_tag, image_caption_tag ]  
